### ISSUE TITLE
KeyError: 1501

### ISSUE THREAD

**Issue by hallonstedt** [trafiklab/gtfs-examples#3]
I have tried to get departures from Höllviken Centrum (Stop ID: 9021012033015000) but the received response generates an error that I have failed to figure out. I get instant results using any other Stop ID (I tried at least 10 others and they all work)
```

2022-11-05 11:36:00,375 - root - DEBUG - Getting related stops
2022-11-05 11:36:00,375 - root - DEBUG - Getting stop times for stops
2022-11-05 11:36:00,375 - root - DEBUG - Filtering stop times
2022-11-05 11:36:00,376 - root - DEBUG - Compiling results
2022-11-05 11:36:00,377 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): opendata.samtrafiken.se:443
2022-11-05 11:36:00,463 - urllib3.connectionpool - DEBUG - https://opendata.samtrafiken.se:443 "GET /gtfs-rt/skane/TripUpdates.pb?key=xxxxxxxxxxxxxxxxxxxx HTTP/1.1" 200 None
2022-11-05 11:36:00,517 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): opendata.samtrafiken.se:443
2022-11-05 11:36:00,598 - urllib3.connectionpool - DEBUG - https://opendata.samtrafiken.se:443 "GET /gtfs-rt/skane/VehiclePositions.pb?key=xxxxxxxxxxxxxxxxxxxx HTTP/1.1" 200 None
2022-11-05 11:36:00,622 - TimeTableApi - ERROR - Exception on /departures/9021012033015000 [GET]
Traceback (most recent call last):
File "/home/hallonstedt/.local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app response = self.full_dispatch_request()
File "/home/hallonstedt/.local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request rv = self.handle_user_exception(e)
File "/home/hallonstedt/.local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request rv = self.dispatch_request()
File "/home/hallonstedt/.local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/var/www/gtfs-examples/python/gtfsToTimetableApi/TimeTableApi.py", line 31, in departures resp = flask.Response(json.dumps(query_engine.create_departures_timetable(stop_id)))
File "/var/www/gtfs-examples/python/gtfsToTimetableApi/GtfsTimeTable.py", line 131, in create_departures_timetable return self._compile_results(stop_times_in_window, query_stop_ids)
File "/var/www/gtfs-examples/python/gtfsToTimetableApi/GtfsTimeTable.py", line 274, in _compile_results "type": ROUTE_TYPE_NAMES[int(route['route_type'])],

KeyError: 1501

2022-11-05 11:36:00,622 - werkzeug - INFO - 192.168.10.10 - - [05/Nov/2022 11:36:00] "GET /departures/9021012033015000 HTTP/1.1" 500 -


```
Environment: 

- Debian Linux 9.6
- Python 3.9.15
- Flask 2.1.0 (1.1.2 as indicated in requirements.txt is not compatible with jinja2 : ImportError: cannot import name 'escape' from 'jinja2')
- gtfs-realtime-bindings 0.0.7
- urllib3 1.26.5
- requests 2.25.1
- protobuf 3.20.0

**Comment by hallonstedt** [comment]
Problem solved. A ROUTE_TYPE called "NÄRTRAFIK" has been added but is not a part of the hard-coded dictionary in GtfsTimeTable.py.

```
diff org.GtfsTimeTable.py new.GtfsTimeTable.py
22a23
>     1501: "NÄRTRAFIK",
```
